version: "3.9"

services:
  back:
    container_name: vacancy_back
    build:
      context: ./vacancy_back
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  front:
    container_name: vacancy_front
    build:
      context: ./vacancy_front
      dockerfile: Dockerfile